workflows:
  dailyhub_android:
    name: DailyHub Android
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Create Android project
        script: flutter create . --platforms=android

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
